### ISSUE TITLE
Fails to build on cuda_12.4.r12.4/compiler.34097967_0 w/ clang or gcc

### ISSUE THREAD

**Issue by grinapo** [EricLBuehler/mistral.rs#1776]
## Minimum reproducible example
Latest pull doesn't compile, gcc fills the stack, clang (14,17,19) produces output.

## Error
https://paste.grin.hu/nJWVwYWo

error: failed to run custom build command for `candle-kernels v0.9.2-alpha.1 (https://github.com/huggingface/candle.git?rev=d91be02#d91be02f)`

### clang-14
```
  /usr/include/x86_64-linux-gnu/bits/mathcalls.h:79:15: error: exception specification in declaration does not match previous declaration
  extern double cospi(double __x) noexcept(true); extern double __cospi(double __x) noexcept(true); 
                ^
  /usr/include/crt/math_functions.h:5554:15: note: previous declaration is here
  extern double cospi(double x); 
                ^
  /usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:15: error: exception specification in declaration does not match previous declaration
  extern double sinpi(double __x) noexcept(true); extern double __sinpi(double __x) noexcept(true); 
                ^
  /usr/include/crt/math_functions.h:5442:15: note: previous declaration is here
  extern double sinpi(double x); 
                ^
  /usr/include/x86_64-linux-gnu/bits/mathcalls.h:79:14: error: exception specification in declaration does not match previous declaration
  extern float cospif(float __x) noexcept(true); extern float __cospif(float __x) noexcept(true); 
               ^
  /usr/include/crt/math_functions.h:5606:14: note: previous declaration is here
  extern float cospif(float x); 
               ^
  /usr/include/x86_64-linux-gnu/bits/mathcalls.h:81:14: error: exception specification in declaration does not match previous declaration
  extern float sinpif(float __x) noexcept(true); extern float __sinpif(float __x) noexcept(true); 
               ^
  /usr/include/crt/math_functions.h:5502:14: note: previous declaration is here
  extern float sinpif(float x); 
               ^
```

### clang-19 (and -21)
```
  /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/type_traits(3192): error: type name is not allowed
            bool _Dangle = __reference_converts_from_temporary(_Tp, _Res_t)
                                                               ^

  /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/type_traits(3192): error: type name is not allowed
            bool _Dangle = __reference_converts_from_temporary(_Tp, _Res_t)
                                                                    ^
 
  /usr/lib/gcc/x86_64-linux-gnu/15/../../../../include/c++/15/type_traits(3192): error: identifier "__reference_converts_from_temporary" is undefined
            bool _Dangle = __reference_converts_from_temporary(_Tp, _Res_t)
                           ^
```

## Other information
Please specify:
- Operating system: Debian sid
- GPU or accelerator information
    - Build cuda_12.4.r12.4/compiler.34097967_0
    - NVIDIA GeForce RTX 4070 12282MiB

## Latest commit or version
- commit 95fc72243b4d06e248a52ea09a448c022f9672f0 (origin/master)

**Comment by grinapo** [comment]
**Doing rustup** from 1.91.4 **to 1.92** makes it compile by gcc or clang 21.
I hope this helps others looking for this.
