### PR TITLE
fix(cuda): restore GB10 builds with cudaforge 0.1.6

### LINKED ISSUE #2414: build install fails on GB10: error[E0061]: this method takes 6 arguments but 5 arguments were supplied
## Minimum reproducible example
The minimum example to reproduce the error. Simpler examples make it easier and faster to fix!

cargo install --path mistralrs-cli --features "cuda flash-attn"

## Error
What is the error? If the error is very long, please try to extract an excerpt of it and post a link to a [Gist](https://gist.github.com/)

   Compiling mistralrs-core v0.9.2 (/home/mattia/mistral.rs/mistralrs-core)
error[E0061]: this method takes 6 arguments but 5 arguments were supplied
   --> mistralrs-core/build.rs:175:18
    |
175 |                 .with_git_dependency(
    |                  ^^^^^^^^^^^^^^^^^^^
...
180 |                     false,
    |                     ----- argument #5 of type `Vec<&str>` is missing
    |
note: method defined here
   --> /home/mattia/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cudaforge-0.1.6/src/builder.rs:190:12
    |
190 |     pub fn with_git_dependency(
    |            ^^^^^^^^^^^^^^^^^^^
help: provide the argument
    |
175 |                 .with_git_dependency(
...
179 |                     vec!["include"],
180 ~                     /* Vec<&str> */,
181 ~                     false,
    |

For more information about this error, try `rustc --explain E0061`.
error: could not compile `mistralrs-core` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

## Other information
Please specify:
- Operating system (Windows, MacOS, WSL2, Linux, etc)
- GPU or accelerator information
    - If CUDA, please run `nvcc --version`, `nvidia-smi`

(base) mattia@zgx-0bb5:~/mistral.rs$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Aug_20_01:57:39_PM_PDT_2025
Cuda compilation tools, release 13.0, V13.0.88
Build cuda_13.0.r13.0/compiler.36424714_0

(base) mattia@zgx-0bb5:~/mistral.rs$ nvidia-smi
Fri Sep  4 18:46:37 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.173.02             Driver Version: 580.173.02     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GB10                    On  |   0000000F:01:00.0 Off |                  N/A |
| N/A   40C    P8              4W /  N/A  | Not Supported          |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            2768      G   /usr/lib/xorg/Xorg                       18MiB |
|    0   N/A  N/A            2968      G   /usr/bin/gnome-shell                      6MiB |
+-----------------------------------------------------------------------------------------+

## Latest commit or version
Which commit or version you ran with.

### PR DESCRIPTION
**Pull request by sizzlecar**
Fixes #2414.

Cargo install resolves workspace dependencies without relying on the repository lockfile. The existing cudaforge range therefore selected 0.1.6, while mistralrs-core still called its old five-argument API.

This updates the call for the extra sparse-checkout paths argument and pins 0.1.6 exactly. Keeping 0.1.6 matters for GB10 because it adds SM121f architecture handling; the exact pin also prevents another incompatible 0.1.x patch from breaking unlocked installs.

Validation:

- RTX 4050 CUDA build compiled and ran the mistralrs-core build script without the reported E0061. I stopped the later full GDN kernel compilation after about seven minutes.
- Cargo metadata with the lockfile passes.
- The CUDA feature graph resolves cudaforge 0.1.6.
- Changed Rust file formatting and git diff checks pass.

The reporter's GB10 is still the best place to confirm the complete original cargo install command.

### CODE REVIEW

**Review by EricLBuehler — APPROVED** [review]
Thanks @sizzlecar!
